# Configuration for desktop (Linux Mint 20)
# Run with ansible-playbook ~/projects/configure-system/desktop.yml --ask-become-pass

---
- name: My stuff
  hosts: localhost
  connection: local

  tasks:

  - debug:
      msg: "Running for user: {{ ansible_user_id }}"
  
  - name: Enable snaps
    stat: path=/etc/apt/preferences.d/nosnap.pref
    register: snap_stat
    become: true
  
  - name: Enable snaps
    command: mv /etc/apt/preferences.d/nosnap.pref /etc/apt/preferences.d/nosnap.pref.bak
    become: true
    when: snap_stat.stat.exists

  - name: Install snapd
    apt:
      name: snapd
      state: present
      update_cache: yes
    become: true

  - include_tasks: common.yml
  
  - name: Add Nextcloud repository
    shell: add-apt-repository -y ppa:nextcloud-devs/client
    become: true

  - name: Install packages
    apt:
      name:
        - nextcloud-client
        - ssh
        - deja-dup
        - command-not-found # Removed by Mint probably because of the snap fiasco?
        - steam
      state: present
      update_cache: yes
    become: true

  - name: Install snaps
    snap:
      name:
        - openra
        - cherrytree
      state: present
    become: true

##
##
## Personal customisations follow...
##
##

  - name: Remove directories
    file:
      path:  "{{ item }}"
      state: absent
    loop:
      - ~/Pictures
      - ~/Documents
      - ~/Videos

  - name: Create symlinks
    file:
      src:  "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop:
      - { src: Nextcloud/Pictures, dest: ~/Pictures }
      - { src: Nextcloud/Documents, dest: ~/Documents }
      - { src: Nextcloud/Videos, dest: ~/Videos }
      - { src: Nextcloud/.gnupg, dest: ~/.gnupg }

# Semmle
# Add PATH=$PATH:$HOME/codeql-home/codeql-cli to .profile

# Manual Tasks
# Set up dejadup to NAS
# Install Beyond Compare
# sudo dpkg-reconfigure wireshark-common (enable wireshark group)
# Add user to wireshark group
# Extract android-studio-ide and run to download additional components
