# Configuration for desktop (Linux Mint 20)
# Run with ansible-playbook ~/projects/configure-system/desktop.yml --ask-become-pass

---
- name: My stuff
  hosts: localhost
  connection: local

  tasks:

  - debug:
      msg: "Running for user: {{ ansible_user_id }}"
  
  - name: Enable snaps
    stat: path=/etc/apt/preferences.d/nosnap.pref
    register: snap_stat
    become: true
  
  - name: Enable snaps
    command: mv /etc/apt/preferences.d/nosnap.pref /etc/apt/preferences.d/nosnap.pref.bak
    become: true
    when: snap_stat.stat.exists

  - name: Install snapd
    apt:
      name: snapd
      state: present
      update_cache: yes
    become: true

  - include_tasks: common.yml
  
  - name: Add Nextcloud repository
    shell: add-apt-repository -y ppa:nextcloud-devs/client
    become: true

  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    become: true
    loop:
      - nextcloud-client
      - ssh
      - deja-dup

  - name: Install snaps
    snap:
      name: "{{ item }}"
      state: present
    become: true
    loop:
      - openra
      - cherrytree

  - name: Remove directories
    file:
      path:  "{{ item }}"
      state: absent
    loop:
      - ~/Pictures
      - ~/Documents
      - ~/Videos

  - name: Create symlinks
    file:
      src:  "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop:
      - { src: Nextcloud/Pictures, dest: ~/Pictures }
      - { src: Nextcloud/Documents, dest: ~/Documents }
      - { src: Nextcloud/Videos, dest: ~/Videos }
      - { src: Nextcloud/.gnupg, dest: ~/.gnupg }

  - name: FileZilla dependencies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    become: true
    loop:
      - libtool
      - nettle-dev
      - libgnutls28-dev
      - libwxgtk3.0-gtk3-dev
      - libpugixml-dev
      - libgtk-3-dev
      - libsqlite3-dev
  