# Configuration for laptop (Ubuntu 20.04)
# Run with ansible-playbook ~/projects/configure-system/laptop.yml --ask-become-pass

---
- name: My stuff
  hosts: localhost
  connection: local

  tasks:

  - debug:
      msg: "Running for user: {{ ansible_user_id }}"

  - include_tasks: common.yml
  
  - name: Add Nextcloud repository
    apt_repository:
      repo: 'ppa:nextcloud-devs/client'
    become: true

  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    become: true
    loop:
      - gnome-tweaks
      - dconf-editor
      - nextcloud-client
      - tlp
      - lollypop
      - indicator-multiload

  - name: Install snaps
    snap:
      name: "{{ item }}"
      state: present
    become: true
    loop:
      - openra
      # - cherrytree # Removed as doesn't yet support HiDPI. Building own.

##
##
## Personal customisations follow...
##
##

  - name: Remove directories
    file:
      path:  "{{ item }}"
      state: absent
    loop:
      - ~/Pictures
      - ~/Documents
      - ~/Videos

  - name: Create symlinks
    file:
      src:  "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop:
      - { src: Nextcloud/Pictures, dest: ~/Pictures }
      - { src: Nextcloud/Documents, dest: ~/Documents }
      - { src: Nextcloud/Videos, dest: ~/Videos }
      - { src: Nextcloud/.gnupg, dest: ~/.gnupg }
      - { src: Nextcloud/Pictures.RAW, dest: ~/Pictures.RAW }
    
  - name: Music sync cronjob
    cron:
      name: "music sync"
      minute: "0"
      hour: "*"
      job: "rsync -xav --delete /home/{{ ansible_user_id }}/Music/ {{ ansible_user_id }}stor:media/music"

  - name: Pictures sync cronjob
    cron:
      name: "pictures sync"
      minute: "0"
      hour: "*"
      job: "rsync -xav --delete --exclude=Wallpapers /home/{{ ansible_user_id }}/Pictures/ {{ ansible_user_id }}stor:media/pictures"

  # - name: Disable touchstreen - x11 (doesn't work on Wayland)
  #   lineinfile:
  #     path: ~/.profile
  #     regexp: "xargs xinput disable"
  #     line: "xinput | egrep 'xwayland-touch|ELAN' | grep -Po 'id=\\d+' | cut -d= -f2 | xargs xinput disable"

  - name: Spotify HiDPI fix
    copy:
      src: /snap/spotify/current/meta/gui/spotify.desktop
      dest: ~/.local/share/applications/spotify.desktop
      mode: +x

  - name: Spotify HiDPI fix
    lineinfile:
      path: ~/.local/share/applications/spotify.desktop
      regexp: "Icon="
      line: "Icon=/snap/spotify/current/usr/share/spotify/icons/spotify-linux-128.png"

  - name: Spotify HiDPI fix
    lineinfile:
      path: ~/.local/share/applications/spotify.desktop
      regexp: "Exec="
      line: "Exec=spotify --force-device-scale-factor=2.0 %U"

  - name: Spotify HiDPI fix
    lineinfile:
      path: ~/.local/share/applications/spotify.desktop
      regexp: "Name="
      line: "Name=Spotify (HiDPI)"

# Semmle
# Add PATH=$PATH:$HOME/codeql-home/codeql-cli to .profile

# Manual Tasks
# Set up dejadup to NAS
# Enable livepatch
# Install Beyond Compare
# sudo dpkg-reconfigure wireshark-common (enable wireshark group)
# Add user to wireshark group
# Extract android-studio-ide and run to download additional components
